// Jenkinsfile (Declarative Pipeline)

pipeline {
    // 1. Define Agent Environment: Uses the containerized environment for running tests.
    agent {
        docker {
            image 'markhobson/maven-chrome:latest' 
            // FINAL FIX: Mapping the host's .m2 cache to the container's standard Jenkins user home directory
            args '-v /dev/shm:/dev/shm -v /var/lib/jenkins/.m2:/home/jenkins/.m2' 
        }
        
    }

    // 2. Define Environment Variables: Passes configuration to the test execution.
    environment {
        // CRITICAL: Replace with your actual EC2 Public IP address and Port 80
        APP_URL = 'http://13.60.210.62:80' 
        // Credential ID set up in Jenkins (your GitHub PAT)
        GH_CREDS = 'github-pat-creds' 
        // Instructor's email for notification, as required for the collaborator who pushed.
        COLLAB_EMAIL = 'Qasim.Malik@comsats.edu.pk' // Replace with the actual email
    }

    // 3. Define Pipeline Stages
    stages {
        stage('Checkout Test Code') {
            steps {
                echo 'Checking out Selenium test code from GitHub...'
                // Fetches the test code repository using stored credentials
                git branch: 'main', credentialsId: GH_CREDS, url: 'https://github.com/IrfaanDS/flask-app-test-code' 
            }
        }

        stage('Execute Selenium Tests') {
            steps {
                echo "Running containerized Maven tests against ${APP_URL}..."
                // Runs tests, passing the live URL as a system property (-Dapp.url).
                sh "mvn clean test -Dapp.url=${APP_URL}" 
            }
        }

        stage('Publish Test Results') {
            steps {
                echo 'Publishing JUnit test reports for Jenkins dashboard...'
                // Parses the XML reports generated by the Surefire plugin.
                junit 'target/surefire-reports/*.xml' 
            }
        }
    }

    // 4. Post-Build Actions (Correctly placed at the top level, resolving the error)
    // This section is required for email notification.
    post {
        // Runs regardless of the stage result
        always {
            // Clean up the Jenkins workspace after the build
            cleanWs()
        }
        success {
            echo "Build successful. Notifying collaborator at ${COLLAB_EMAIL}."
            // NOTE: You must configure the Jenkins Mailer Plugin globally for this to send.
            // mail to: env.COLLAB_EMAIL, subject: "SUCCESS: Pipeline ${env.JOB_NAME} #${env.BUILD_NUMBER}", body: "Tests passed. See report: ${env.BUILD_URL}/testReport"
        }
        failure {
            echo "Build failed. Notifying collaborator at ${COLLAB_EMAIL}."
            // mail to: env.COLLAB_EMAIL, subject: "FAILURE: Pipeline ${env.JOB_NAME} #${env.BUILD_NUMBER}", body: "Tests failed. Review report: ${env.BUILD_URL}/testReport"
        }
    }
}